export const TRAINING_PHOTO_MAX_COUNT = 1
export const TRAINING_PHOTO_MAX_FILE_SIZE_BYTES = 15 * 1024 * 1024
export const TRAINING_PHOTO_COMPRESS_MAX_EDGE_PX = 1600
export const TRAINING_PHOTO_COMPRESS_TARGET_BYTES = 900 * 1024
